### ISSUE TITLE
Implement componentWillUnmount

### ISSUE THREAD

**Issue by etienne-dldc** [adamjking3/react-typing-animation#1]
Hi ✋ ,

When a `Typing` component is unmounted while Typings is in progress the timer is not canceled and a `setState` is trigger on the unmounted component which log an Error.

To solve this you should implement `componentWillUnmount` on `Typing` component and stop the typing loop.

**Comment by adamjking3** [comment]
Hi @etienne-dldc ✋,
Thanks for pointing that out! Would you mind submitting a Pull Request with a solution to this problem? I'm a little too busy currently to work on this project, but I'd be happy to review a PR and merge it if everything looks good! If not, no worries, I'll get to it when I've got some free time.
