### ISSUE TITLE
Import files wrong 

### ISSUE THREAD

**Issue by RobinHerzog** [adamjking3/react-typing-animation#12]
Hi there,

I'm new to React, so I'm sure this is a basic mistake.

https://www.dropbox.com/s/2h4ewem323b4b5t/Capture%20d%27%C3%A9cran%202018-04-05%2017.39.40.png?dl=0

I got that errors while importing this module. Any idea ?

**Comment by alberttoledo** [comment]
I get the same. It may be a problem with the latest version.

**Comment by adamjking3** [comment]
I can't seem to replicate this problem. Are you using v1.3.0?

**Comment by adamjking3** [comment]
Can either of you post a snippet of the code you're using that is causing the error? @RobinHerzog Are you using create-react-app?

**Comment by alberttoledo** [comment]
@adamjking3 thanks for the quick response. Just the import itself is doing it. But yeah I am using create-react-app.

Here is where the error is happening:
![image](https://user-images.githubusercontent.com/13247259/38448416-04d52114-39d2-11e8-8920-3b9328041e03.png)

**Comment by adamjking3** [comment]
Try v1.3.2, I changed the build config in the 1.3.0 update and it seems to be breaking in older browsers.

**Comment by alberttoledo** [comment]
Awesome! thanks so much, trying now.

**Comment by alberttoledo** [comment]
@adamjking3 It works! You are the king

**Comment by adamjking3** [comment]
Glad to hear it! Thanks for letting me know about that!
