### ISSUE TITLE
The page crashes when you return to the component.

### ISSUE THREAD

**Issue by alex-knyazev** [adamjking3/react-typing-animation#13]
In version 1.3.3 when I open page which contains Typing-component, all works. After I click to `<Link />` component from react-router and page chushed with error "Uncaught TypeError: Converting circular structure to JSON"
If I use 1.3.2 - all works.
You can look at my example: https://github.com/alex-knyazev/alex-knyaz/tree/show-typing-error

**Comment by archieherbias** [comment]
Also encountered this one when calling `setState` during `onFinishedTyping`.

**Comment by Amurmurmur** [comment]
+1

**Comment by kvss1992** [comment]
Backspace props are broken in the 1.3.2 
`<Typing>
    <span>This span will get typed, then erased.</span>
    <Typing.Backspace count={20} />
    <span>Text 2.</span>
  </Typing>`

Both the text would be printed finally. 
Any solution to this Backspace Component? 
Thank you

**Comment by bretthayes** [comment]
I also rolled back to 1.3.2 and it works. ✨ 

My problem was that the page was crashing using 1.3.3 since I `setState` for `onFinishedTyping` to reset the word being typed. The word is a child of the Typing component. I guess it doesn't like undefined before the word is reset?

You can check out my implementation on our site at [www.taurus.io](https://taurus.io).

**Comment by diegohaz** [comment]
Any updates on this?

**Comment by adamjking3** [comment]
@bretthayes love the implementation. The project/site looks really cool, good luck on the upcoming ICO!

About the issue, I apologize but I am currently swamped with work. The SaaS I've been building for the past year was just released to Beta customers this month, so all of my free time is required there. I will however review/accept any PRs.

**Comment by nicer00ster** [comment]
Man this wasn't happening at all and I've been working on my project for months now. I added npm install -g compression and somehow it broke, giving me the JSON circular nonsense. I even removed compression and it's still breaking T_T

**Comment by adamjking3** [comment]
This should be fixed in v1.3.4. Let me know if it's not.

**Comment by toniton** [comment]
This issue has not been fixed.

> This should be fixed in v1.3.4. Let me know if it's not.
