### ISSUE TITLE
Error in the while loop at line 188 typings.js

### ISSUE THREAD

**Issue by flasd** [adamjking3/react-typing-animation#2]
When the backspace count is bigger then the number of letters, the promise throws and error and exists, stoping all the animation.

```jsx
<Typing speed={100} loop={true} cursor={Cursor} >
    <span>Apps</span>
    <Typing.Backspace count={8} speed={30} />
</Typing>
```
Thrown error: 

> Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at Typing.js:188

Line 188 is this:

> cursor.charPos = text[cursor.lineNum].length ? text[cursor.lineNum].length - 1 : 0;

**Comment by adamjking3** [comment]
Hi @flasd, thanks for contributing! Would you mind submitting a Pull Request with the solution to the bug? I'm a little too busy currently to work on this project, but I'd be happy to review a PR and merge it if everything looks good! If not, no worries, I'll get to it when I've got some free time.
