### ISSUE TITLE
Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by gijo-varghese** [adamjking3/react-typing-animation#22]
I've the set the component like this:
```
<Typing loop style={{ display: "inherit" }}>
  <span>
    Newsletters{" "}
    <img alt="📰" src="/static/emoji/np.png" width="30px" />
  </span>
  <Delay ms={2000} />
  <Backspace count={21} />
  <span>
    Content Updates{" "}
    <img alt="✍️" src="/static/emoji/write.png" width="30px" />
  </span>
  <Delay ms={2500} />
  <Backspace count={25} />
</Typing>
```

But I'm seeing getting the warning: `Each child in an array or iterator should have a unique "key" prop`

I tried setting `key` to both `span` and `img`, didn't work!

**Comment by gijo-varghese** [comment]
@adamjking3 tried that. Getting error: `span: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)`

**Comment by jasperdg** [comment]
Any update on this :)

**Comment by BeardDude** [comment]
> @adamjking3 tried that. Getting error: `span: `key`is not a prop. Trying to access it will result in`undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)`

@gijo-varghese On passing unique key value to all the children of Typing, helps in getting rid of that warning. For example adding something like

`<Typing loop>`
 `<span key={Math.random()} className="hello">`
                  `Hello! 👋`
` </span>`
`<Typing.Delay key={Math.random()} ms={1200} />`
`</Typing>` 

**works.**

But, If you need to access those elements individually then we need to work on an enhancement as suggested by @adamjking3

**Comment by adamjking3** [comment]
This should be fixed in the latest release on npm.
