### ISSUE TITLE
No Option for Default String/ Array of Strings

### ISSUE THREAD

**Issue by danielnmai** [adamjking3/react-typing-animation#25]
2 feature suggestions I could think of for your component:

1. It does not work with an array of strings. For multiple typed strings (and backspace effect), we need to use many <span> elements. No way around it. I've used many other libraries, and they always have an option to accept an array of strings. Something like this:
```javascript
const options = {
      strings: [
        'Full-Stack Developer', 'Front End Developer', 'Web Designer'
      ]}
new TypeIt(this.el, options)
```

2. It does not have a default string when the typing effect ends. Right now I use state to achieve the purpose, but it would be nice to have a defaultString option when the typing effect is finished.

```javascript
class TypedString extends Component {
  constructor(){
    super()
    this.state = {isFinished: false}
  }
  isFinishedTyping = () => {
    this.setState({isFinished: true})
  }
  render() {
    let typedString
    if(this.state.isFinished){
      typedString = <span>Full-Stack Developer</span>
    } else {
      typedString = (
        <div>
          <Backspace count={20}/>
          <span>Software Engineer</span>
          <Delay ms={1000} />
          <Backspace count={20} />
          <span>Front End Developer</span>
          <Delay ms={1000} />
          <Backspace count={20}/>
          <span>Full-Stack Developer</span>
        </div>
      )
    }
    return (
      <Typing speed= {100} cursorClassName="cursor" onFinishedTyping={() => this.isFinishedTyping() } >
        {typedString}
      </Typing>      
    )    
  }
}
export default TypedString;
```

I can have a look at the source code and will see if I can add something to it.

**Comment by danielnmai** [comment]
@Jerga99 How can you handle default string after the effect is finished?

**Comment by Jerga99** [comment]
@danielnmai 
let's try this here is working example, my previous code was out of context:

constructor() {
super();

    this.state = {
      typerIndex: 0,
    }

    this.roles = ['Developer', 'Designer', 'Project Leader', 'Course Creator', 'Tech Lover'];
}
 componentDidMount() {
    this._isMounted = true
  }

  componentWillUnmount() {
    this._isMounted = false
    if (this.timer) {
      clearTimeout(this.timer)
    }
  }

  onTypingDone() {
    this.timer = setTimeout(this.playNext, 1000)
  }

  playNext() {
    const { typerIndex } = this.state

    this.setState({
      typerIndex: (typerIndex + 1) % this.roles.length
    });
  }

  renderInLoop() {
    const {typerIndex } = this.state;

    return this.roles.map((role, index) =>{
      if (index === typerIndex) {
        return (
            <Typing key={index} onFinishedTyping={() => {this.onTypingDone()}} cursorClassName="typed-cursor">
              <span className="self-typed">{role}.</span>
              <Typing.Backspace cursorClassName="typed-cursor"  speed={80} count={20} delay={1000} />
            </Typing>
        )
      }
    });
  }
