### ISSUE TITLE
Always scroll up in an overflowed container

### ISSUE THREAD

**Issue by doumart** [adamjking3/react-typing-animation#29]
I don't know if it is possible but it could be convinient to scroll at the bottom instead to follow the new letters displayed.

**Comment by adamjking3** [comment]
This should now be possible using the new `onTyping` method. A modification of the following code should do the trick:

```js
<Typing
    {...otherProps}
    onTyping={() => { window.scrollTop = window.scrollHeight; }}
/>
```
