### ISSUE TITLE
Babel runtime error

### ISSUE THREAD

**Issue by ashishcodes4** [adamjking3/react-typing-animation#34]
I just following the initial steps for getting started, as mentioned I started with installing the module form npm and then, import the Typing module, using corresponding JSX code I am trying to get the typing effect added but instead I am getting an error message in my terminal.
![screenshot 2018-12-24 at 11 41 09 pm](https://user-images.githubusercontent.com/28031165/50405075-6f679a80-07d5-11e9-9747-157698b2b6e4.png)
This is the exact message I am getting after I have followed the mentioned steps, any ideas why this would happen. 
TIA!!

**Comment by ashishcodes4** [comment]
This is resolved, in fact there was nothing wrong, I just had the library added in the wrong location. 
Sorry to bother. 
Thanks!

**Comment by insivika** [comment]
Please Ashish please elaborate. I'm having the same issue and don't seem to be able to figure this out.

**Comment by hmajid2301** [comment]
I solved it by adding babel runtime to my dependencies `yarn add babel-runtime`
