### ISSUE TITLE
Hide cursor after typing?

### ISSUE THREAD

**Issue by adamgruber** [adamjking3/react-typing-animation#7]
I don't see an option for hiding the cursor when typing is finished. Is there a way to do this?

**Comment by adamjking3** [comment]
Hi, unfortunately I do not have time to work on this project right now because I am so busy with work. I am however willing to review and accept pull requests if anyone would like to fix this or any other bugs found.

**Comment by adamjking3** [comment]
I have added this feature to v1.3.0.
