### ISSUE TITLE
Change cursor color to white

### ISSUE THREAD

**Issue by rendellpierre** [adamjking3/react-typing-animation#8]

**Comment by rendellpierre** [comment]
It would be nice but not a big issue. but it would be nice.

**Comment by adamjking3** [comment]
Hi, unfortunately I do not have time to work on this project right now because I am so busy with work. I am however willing to review and accept pull requests if anyone would like to fix this or any other bugs found.

**Comment by adamjking3** [comment]
I am adding a property `cursorClassName` to the Typing component, which will allow you to set styles on the cursor component, does this fit your use case?

**Comment by adamjking3** [comment]
This should be fixed in v1.3.0.

**Comment by sappusaketh** [comment]
Can you paste code how to pass
