### ISSUE TITLE
React v16 compatability

### ISSUE THREAD

**Issue by zaruda** [adamjking3/react-typing-animation#9]
react v16 unsupported
https://monosnap.com/file/SDsgsfldCgHG9wOvuGsTKzzMl8JjPc

**Comment by danidewitt** [comment]
+1

**Comment by danidewitt** [comment]
https://github.com/facebook/react/issues/10320 . "Please run npm ls react. You'll find that some package brings in the wrong version of React because it puts it in dependencies rather than peerDependencies. Please file an issue with that project."

**Comment by zaruda** [comment]
@danidewitt yep, also saw this solution. But I found the better way - change this one to another plugin )

**Comment by danidewitt** [comment]
@zaruda yeah, i switched to https://github.com/jstejada/react-typist

**Comment by nanocreaator** [comment]
Latest React

TypeError: this.updater.enqueueCallback is not a function. (In 'this.updater.enqueueCallback(this, callback, 'setState')', 'this.updater.enqueueCallback' is undefined)

**Comment by adamjking3** [comment]
Hi, unfortunately I do not have time to work on this project right now because I am so busy with work. I am however willing to review and accept pull requests if anyone would like to fix this or any other bugs found.

**Comment by gbenson-wikia** [comment]
Odds on getting that PR merged anytime soon?

**Comment by gbenson-wikia** [comment]
Thanks!  I look forward to seeing the updated version on npm soon.  😄
